In [6]:
# Basics of TensorFlow and Keras
# setting up TensorFlow
import tensorflow as tf
import keras
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/anton/miniforge3/envs/ml/lib/python3.11/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [7]:
# Create a tensor which is an array
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
# tensor math and manipulation
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])


c = tf.add(a, b)
print(c)
d = tf.multiply(a, b)
print(d)
e = tf.subtract(a, b)
print(e)
f = tf.divide(a, b)
print(f)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [9]:
# manipulating tensor attributes
print(tensor.shape)  # Shape of the tensor
print(tensor.dtype)  # Data type of the tensor



(2, 2)
<dtype: 'int32'>


In [10]:
# using tensorflow functions
zeros = tf.zeros([3, 3])  # 3x3 matrix of zeros
ones = tf.ones([3, 3])    # 3x3 matrix of ones
random = tf.random.normal([3, 3], mean=2, stddev=1)  # Random normal distribution
print(random)


tf.Tensor(
[[2.2494526 1.5793092 2.0748093]
 [1.1085639 1.1654286 3.2950633]
 [1.7723502 1.5954139 1.2982993]], shape=(3, 3), dtype=float32)


In [11]:
# converting numpy to tensorflow
import numpy as np
array = np.array([1, 2, 3])
tensor = tf.convert_to_tensor(array)
print(tensor)


tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [12]:
# tensorflow variables
var = tf.Variable([1.0, 2.0, 3.0])
print(var)
var.assign([4.0, 5.0, 6.0])  # Assign new values
print(var)


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>


In [13]:
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [14]:
# building a simple Sequential model
# Sequential is useful for stacking layers where each layer has one input tensor and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers.
# For each example, the model returns a vector of logits or log-odds scores, one for each class.

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [15]:

predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.33905154, -0.72344476,  0.45500445,  0.29599577, -0.18545972,
        -0.23216842,  0.11630823, -0.03827632,  0.7162858 , -0.05921811]],
      dtype=float32)

In [16]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
tf.nn.softmax(predictions).numpy()

array([[0.1219689 , 0.04215147, 0.13696411, 0.11682887, 0.07218663,
        0.06889241, 0.09761418, 0.083633  , 0.17786063, 0.08189978]],
      dtype=float32)

In [ ]:
#
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)