In [78]:
import tensorflow as tf
import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense




In [79]:
# Create a tensor which is an array
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [80]:
# tensor math and manipulation
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])


c = tf.add(a, b)
print(c)
d = tf.multiply(a, b)
print(d)
e = tf.subtract(a, b)
print(e)
f = tf.divide(a, b)
print(f)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [81]:
# manipulating tensor attributes
print(tensor.shape)  # Shape of the tensor
print(tensor.dtype)  # Data type of the tensor



(2, 2)
<dtype: 'int32'>


In [82]:
# using tensorflow functions
zeros = tf.zeros([3, 3])  # 3x3 matrix of zeros
ones = tf.ones([3, 3])    # 3x3 matrix of ones
random = tf.random.normal([3, 3], mean=2, stddev=1)  # Random normal distribution
print(random)


tf.Tensor(
[[2.0429883 2.380245  1.9222012]
 [1.6918265 2.0233934 1.6603146]
 [2.0601664 2.623907  3.745914 ]], shape=(3, 3), dtype=float32)


In [83]:
# converting numpy to tensorflow
import numpy as np
array = np.array([1, 2, 3])
tensor = tf.convert_to_tensor(array)
print(tensor)


tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [84]:
# tensorflow variables
var = tf.Variable([1.0, 2.0, 3.0])
print(var)
var.assign([4.0, 5.0, 6.0])  # Assign new values
print(var)


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>


In [85]:
# Gradient Computation with Autograd using tf.GradientTape
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2

# Compute the gradient of y with respect to x
grad = tape.gradient(y, x)
print(grad)


tf.Tensor(6.0, shape=(), dtype=float32)


In [86]:
# How to Define a Model
# Build a simple model
model = Sequential([
    Dense(10, activation='relu', input_shape=(5,)),
    Dense(1, activation='linear')
])

model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 10)             │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (284.00 B)

 Trainable params: 71 (284.00 B)

 Non-trainable params: 0 (0.00 B)

In [87]:
# Compile the model
model.compile(optimizer='adam',
              loss='mse',  # Mean squared error
              metrics=['mae'])  # Mean absolute error


In [88]:
# train the model
import numpy as np

# Generate dummy data
x_train = np.random.rand(100, 5)  # 100 samples, 5 features each
y_train = np.random.rand(100, 1)  # 100 labels

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=32)


Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 1.5193 - mae: 1.1777  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4192 - mae: 1.1386 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3041 - mae: 1.0854 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2300 - mae: 1.0578 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1327 - mae: 1.0039 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0033 - mae: 0.9453 
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9341 - mae: 0.9071 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8570 - mae: 0.8657 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8156 - mae: 0.8387 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7216 - mae: 0.7848 


In [92]:
    # TensorFlow Datasets

import tensorflow_datasets as tfds

# Load a dataset
dataset, info = tfds.load('mnist', as_supervised=True, with_info=True)
print(info)


TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [91]:
def preprocess(image, label):
    image = tf.cast(image, tf.float32) / 255.0  # Normalize to [0, 1]
    return image, label

dataset = dataset.map(preprocess).batch(32)


NameError: name 'dataset' is not defined