In [45]:
# Basics of TensorFlow and Keras:
# setting up TensorFlow
import numpy
import tensorflow as tf
from tensorflow.keras import layers, models
print(tf.__version__)
print(numpy.__version__)

2.13.1
1.24.3


In [46]:
# Create a tensor which is an array
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)
# tensorflow Variables can be changed or updated unlike constants
var = tf.Variable([1, 2, 3])
print("Before update:", var.numpy())

# Update the variable
var.assign([4, 5, 6])
print("After update:", var.numpy())


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Before update: [1 2 3]
After update: [4 5 6]


In [47]:
# tensor math and manipulation
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])


c = tf.add(a, b)
print(c)
d = tf.multiply(a, b)
print(d)
e = tf.subtract(a, b)
print(e)
f = tf.divide(a, b)
print(f)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [48]:
# checking tensorflow properties
tensor = tf.constant([[1, 2], [3, 4]])

print("Shape:", tensor.shape)       # (2, 2)
print("Rank:", tf.rank(tensor))     # 2
print("Data Type:", tensor.dtype)   # int32



Shape: (2, 2)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Data Type: <dtype: 'int32'>


In [49]:
# using tensorflow functions
zeros = tf.zeros([3, 3])  # 3x3 matrix of zeros
ones = tf.ones([3, 3])    # 3x3 matrix of ones
random = tf.random.normal([3, 3], mean=2, stddev=1)  # Random normal distribution
print(random)
# reshaping tensors
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
reshaped = tf.reshape(tensor, (2, 3))
print("Original Shape:", tensor.shape)
print("Reshaped Tensor:\n", reshaped)



tf.Tensor(
[[1.1391778  1.807751   1.4827545 ]
 [2.2253256  0.18257725 1.1821389 ]
 [3.5470328  2.2862647  3.2341652 ]], shape=(3, 3), dtype=float32)
Original Shape: (3, 2)
Reshaped Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [50]:
# converting numpy to tensorflow
import numpy as np
array = np.array([1, 2, 3])
tensor = tf.convert_to_tensor(array)
print(tensor)


tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [51]:
# Broadcasting: TensorFlow automatically expands tensors with smaller dimensions to match larger ones during operations.
x = tf.constant([[1, 2, 3]])
y = tf.constant([[1], [2], [3]])
result = tf.add(x, y)  # Broadcasts y to match x
print("Broadcast Result:\n", result)


Broadcast Result:
 tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [52]:
tensor = tf.constant([1, 2, 3])
print("Device:", tensor.device)  # Shows where the tensor is stored


Device: /job:localhost/replica:0/task:0/device:CPU:0


In [53]:
# tensorflow variables
var = tf.Variable([1.0, 2.0, 3.0])
print(var)
var.assign([4.0, 5.0, 6.0])  # Assign new values
print(var)


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>


In [76]:
# loading in a dataset and preprocessing
# Load the dataset
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.fashion_mnist.load_data()

# Normalize the images
train_images = train_images / 255.0
test_images = test_images / 255.0
train_images = train_images[..., tf.newaxis]  # Add a channel dimension for grayscale images
test_images = test_images[..., tf.newaxis]
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = train_dataset.shuffle(buffer_size=10000).batch(32)
train_dataset = train_dataset.batch(32)
test_dataset = tf.data.Dataset.from_tensor_slices((test_images, test_labels)).batch(32)




In [83]:
    #building a model
# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Debug shapes
print("Train images shape:", train_images.shape)  # (60000, 28, 28)
print("Train labels shape:", train_labels.shape)  # (60000,)

# Train the model with batch size 32
model.fit(train_images, train_labels, epochs=10, batch_size=32)



Train images shape: (60000, 28, 28, 1)
Train labels shape: (60000,)
Epoch 1/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4994 - accuracy: 0.8249
Epoch 2/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3750 - accuracy: 0.8640
Epoch 3/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3367 - accuracy: 0.8779
Epoch 4/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3116 - accuracy: 0.8855
Epoch 5/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2957 - accuracy: 0.8910
Epoch 6/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2800 - accuracy: 0.8975
Epoch 7/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2686 - accuracy: 0.9020
Epoch 8/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2580 - accuracy: 0.9044
Epoch 9/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2488 - accuracy: 0.9070
Epoch 10/20
18

In [84]:
# evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
print(f'\nTest accuracy: {test_acc}')


313/313 - 0s - loss: 0.3704 - accuracy: 0.8831 - 402ms/epoch - 1ms/step

Test accuracy: 0.8830999732017517


In [72]:
# saving and loading a model
model.save('my_model.keras')  # Save the entire model
loaded_model = tf.keras.models.load_model('my_model.keras')  # Load it back
