In [49]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist



In [39]:
# Create a tensor which is an array
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [40]:
# tensor math and manipulation
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])


c = tf.add(a, b)
print(c)
d = tf.multiply(a, b)
print(d)
e = tf.subtract(a, b)
print(e)
f = tf.divide(a, b)
print(f)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [41]:
# manipulating tensor attributes
print(tensor.shape)  # Shape of the tensor
print(tensor.dtype)  # Data type of the tensor



(2, 2)
<dtype: 'int32'>


In [42]:
# using tensorflow functions
zeros = tf.zeros([3, 3])  # 3x3 matrix of zeros
ones = tf.ones([3, 3])    # 3x3 matrix of ones
random = tf.random.normal([3, 3], mean=2, stddev=1)  # Random normal distribution
print(random)


tf.Tensor(
[[ 2.011369   2.0946212  2.1868975]
 [ 2.5985415 -0.2769544  1.1245179]
 [ 1.4943987  1.3953772  1.4403389]], shape=(3, 3), dtype=float32)


In [43]:
# converting numpy to tensorflow
import numpy as np
array = np.array([1, 2, 3])
tensor = tf.convert_to_tensor(array)
print(tensor)


tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [44]:
# tensorflow variables
var = tf.Variable([1.0, 2.0, 3.0])
print(var)
var.assign([4.0, 5.0, 6.0])  # Assign new values
print(var)


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>


In [51]:
mnist = tf.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


ModuleNotFoundError: No module named 'keras._tf_keras'