In [57]:
# Basics of TensorFlow and Keras:
# setting up TensorFlow
import tensorflow as tf
from tensorflow.keras import layers, models
print(tf.__version__)

2.13.1


In [58]:
# Create a tensor which is an array
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)
# tensorflow Variables can be changed or updated unlike constants
var = tf.Variable([1, 2, 3])
print("Before update:", var.numpy())

# Update the variable
var.assign([4, 5, 6])
print("After update:", var.numpy())


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Before update: [1 2 3]
After update: [4 5 6]


In [59]:
# tensor math and manipulation
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])


c = tf.add(a, b)
print(c)
d = tf.multiply(a, b)
print(d)
e = tf.subtract(a, b)
print(e)
f = tf.divide(a, b)
print(f)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [60]:
# checking tensorflow properties
tensor = tf.constant([[1, 2], [3, 4]])

print("Shape:", tensor.shape)       # (2, 2)
print("Rank:", tf.rank(tensor))     # 2
print("Data Type:", tensor.dtype)   # int32



Shape: (2, 2)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Data Type: <dtype: 'int32'>


In [61]:
# using tensorflow functions
zeros = tf.zeros([3, 3])  # 3x3 matrix of zeros
ones = tf.ones([3, 3])    # 3x3 matrix of ones
random = tf.random.normal([3, 3], mean=2, stddev=1)  # Random normal distribution
print(random)
# reshaping tensors
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
reshaped = tf.reshape(tensor, (2, 3))
print("Original Shape:", tensor.shape)
print("Reshaped Tensor:\n", reshaped)



tf.Tensor(
[[1.9697186 2.8894181 1.5657136]
 [3.0443532 3.086347  1.9881237]
 [0.8825431 2.189211  1.4287922]], shape=(3, 3), dtype=float32)
Original Shape: (3, 2)
Reshaped Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [62]:
# converting numpy to tensorflow
import numpy as np
array = np.array([1, 2, 3])
tensor = tf.convert_to_tensor(array)
print(tensor)


tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [63]:
# Broadcasting: TensorFlow automatically expands tensors with smaller dimensions to match larger ones during operations.
x = tf.constant([[1, 2, 3]])
y = tf.constant([[1], [2], [3]])
result = tf.add(x, y)  # Broadcasts y to match x
print("Broadcast Result:\n", result)


Broadcast Result:
 tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [64]:
tensor = tf.constant([1, 2, 3])
print("Device:", tensor.device)  # Shows where the tensor is stored


Device: /job:localhost/replica:0/task:0/device:CPU:0


In [65]:
# tensorflow variables
var = tf.Variable([1.0, 2.0, 3.0])
print(var)
var.assign([4.0, 5.0, 6.0])  # Assign new values
print(var)


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>


In [66]:
#Intermeidate Tensorflow and Keras
#Loading in a dataset

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.fashion_mnist.load_data()

print("Training Data Shape:", train_images.shape)  # (60000, 28, 28)
print("Test Data Shape:", test_images.shape)      # (10000, 28, 28)
# common preprocessing of data
train_images, test_images = train_images / 255.0, test_images / 255.0
train_labels = tf.keras.utils.to_categorical(train_labels, num_classes=10)
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = train_dataset.shuffle(buffer_size=10000).batch(32)





Training Data Shape: (60000, 28, 28)
Test Data Shape: (10000, 28, 28)


In [67]:
# Using Pandas or Tensorflow to open csv data
import pandas as pd

# Load data using pandas
df = pd.read_csv("path_to_your_data.csv")
print(df.head())  # Display the first few rows

# Convert to TensorFlow dataset
dataset3 = tf.data.Dataset.from_tensor_slices((df.values[:, :-1], df.values[:, -1]))

# make a csv dataset
dataset4 = tf.data.experimental.make_csv_dataset(
    file_pattern='path_to_your_data.csv',
    batch_size=32,
    label_name='target_column_name',
    num_epochs=1
)

for features, labels in dataset4.take(1):
    print("Features:", features)
    print("Labels:", labels)




FileNotFoundError: [Errno 2] No such file or directory: 'path_to_your_data.csv'

In [68]:
# Basics Building of a model
# build the model
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])



In [69]:
# compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [70]:
# train the model
model.fit(train_images, train_labels, epochs=10)


/Users/anton/miniforge3/envs/ml/lib/python3.11/site-packages/numpy/_typing/_scalars.py:12: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _BoolLike_co: TypeAlias = bool | np.bool


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [13]:
# evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
print(f'\nTest accuracy: {test_acc}')


313/313 - 0s - loss: 0.3359 - accuracy: 0.8834 - 367ms/epoch - 1ms/step

Test accuracy: 0.883400022983551


In [15]:
# saving and loading a model
model.save('my_model.keras')  # Save the entire model
loaded_model = tf.keras.models.load_model('my_model.keras')  # Load it back
